### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by eliascarella** [emiliobondioli/nuxt-magpie#1]
Thank you very much for your work ! Is there any chance of seeing graphql/nuxt-apollo support for this module ? 
I'm trying to build a full static site generator using strapi as a local CMS and this is the last step towards achieving that.. 
Thanks!

**Comment by eppidelic** [comment]
Hi! A local solution with Strapi or similar self hosted CMS is exactly what I had in mind when making this :) what exactly isn't working for you?
Keep in mind that this module only handles image download and replacement, to get the full static generation you need nuxt v2.14+ set up with server side rendering and static target. Once that's setup, during generation nuxt will create a .html file for each route and a 'payload/state.js` file containing the state and data coming from [fetch](https://nuxtjs.org/api/pages-fetch/). One thing I've noticed is that even when full static mode is enabled, nuxt still runs the fetch calls (they mention it [here](https://nuxtjs.org/api/pages-fetch/)) - what I'm doing in my setup is checking if the data already exists in the store (vuex) before making the call.

Once these files are created, Magpie parses them and replaces all remote images with local copies, so it should be independent from the method you use to fetch data, as the page has already been rendered once it runs.

**Comment by eliascarella** [comment]
Hi! Yes so I checked your source-code this morning and I'm not sure why it's not working for me as I can see you look for remote urls in the generated HTML files. 
I checked the HTML files created after running the "nuxt generate" command and the images do have an absolute URL pointing to my (local) server, as so: `<img src="http://localhost:1337/uploads/5_fe31120ddd.jpg" width="100px">`
However I get this in my CLI when I run the "nuxt generate" command. 
`Magpie 0 unique remote images found, saving local copies                                                                                                                          
ℹ Magpie saved 0 remote images `
I'm not sure this is the space for my own little personal case but since my case is quite simple (currently doing testing with <10 images) and not working I thought I'd let you know. 

Again, thanks for starting this project! It seems crucial to me that Nuxt gets this functionality.

**Comment by eppidelic** [comment]
Hmm seems like the regex wasn't picking your image urls, perhaps due to the added port in the url. 
I've updated the regex and tested it with a local strapi install and everything seems to be working fine now (with baseUrl option set to both `''` and `http://localhost:1337`), you can try installing `v0.0.10` and see if it fixes your issue.

I've noticed that strapi does not return the full absolute url of the image (which is a bit weird) but you have to concatenate your base api url to the image urls. This could prevent Magpie from replacing the urls in `payload.js` since no absolute url will be found there. 

I'll look and see if it's viable to use a base directory (`uploads/` in this case) instead of base url for image lookup and replacement, but a temporary solution would be to replace all image urls adding the full url prefix before returning data in the fetch/async.

**Comment by eliascarella** [comment]
Hi again, 
I've updated to latest version and it now works as expected ! But, it wouldn't download because the connection was over http (to my locally running server) and your module expects https. I did update your code myself by changing all connections to http. 
Maybe it's something to consider as an option ? 
Yes you're right strapi's way of returning the url is a bit strange, I concatenate the url myself so the `nuxt generate` returns full url in the HTML code.

Once again thank you for your work, I still can't believe it's not a native option on nuxt, especially for JAMstack type deployments. You're bridging the gap !

**Comment by eppidelic** [comment]
Hi! you're absolutely right! I thought `https` would fall back automatically to `http` like axios does (I was using it to fetch the images before, but decided to remove it as a dependency and use native modules instead). 
I'm now checking for the url protocol before fetching and using `http` or `https` accordingly.

I've also added the `alias` option to correctly replace non-absolute paths when using Strapi, you can read about it in the [readme](https://github.com/emiliobondioli/nuxt-magpie#alias), it may not be working 100% for all cases but for Strapi it seems to be fine.

No worries anyway, thank you for helping me test and debug this! I can understand why the nuxt team doesn't want it in the core, but luckily that's what modules are for ;)
