### ISSUE TITLE
Add support for vuetify <v-img> component

### ISSUE THREAD

**Issue by olivervorasai** [emiliobondioli/nuxt-magpie#2]
### Version
Latest magpie

### Problem
Images defined in the following component are not caught by magpie
```
<v-img :src="urlToSource"></v-img>
```

### Example HTML before generation
```
<v-img :src="generateLink(item.image)"></v-img>
```

### Expected HTML after generation
```
<div data-v-c5bd68cc="" class="v-image v-responsive theme--light">
    <div class="v-responsive__sizer" style="padding-bottom: 75.2%;"></div>
    <div class="v-image__image v-image__image--cover" style="background-image: url("http://localhost:1337/uploads/small_test_Image1_c263df17a1.jpg"); background-position: center center;"></div>
    <div class="v-responsive__content" style="width: 500px;"></div>
</div>
```

### Actual HTML after generation
```
<div class="v-image v-responsive theme--light" data-v-0af97488="">
    <div class="v-image__image v-image__image--preload v-image__image--cover" style="background-position:center center"></div>
    <div class="v-responsive__content"></div>
</div>
```

### Notes
Works fine if just using standard `<img />` tag but this method causes the image to lose the aspect ratio and other stylings that come with vuetify.

**Comment by OliverVorasai** [comment]
@emiliobondioli I have narrowed down the issue to the regex in `module.js`, specifically here:

```
  function getImageUrls (string) {
    const urls = []
    const test = new RegExp(
      '(https?)(://.*?.)(?:' + options.extensions.join('|') + ')',
      'g'
    )
    ...
  }
```

The current regex is generated as:

```
/(https?)(:\/\/.*?.)(?:jpg|jpeg|gif|png|webp)/g   
```

However this pattern doesn't match correct in all cases as seen here: https://regexr.com/5f6ls. As you can see the pattern will match across multiple tags and even across JSON+LD structured data.

I have tried to use a different pattern but I am also issues as well as seen here: https://regexr.com/5f6m2.

**Comment by OliverVorasai** [comment]
Also one more thing, using a CMS like strapi can sometimes generate image URLs that have uppercase extensions like this

```
{
  "id":2,
  "name":"teset",
  "published_at":"2020-10-13T09:33:23.577Z",
  "created_at":"2020-10-13T09:32:51.814Z",
  "updated_at":"2020-10-27T12:25:49.027Z",
  "image":{
    "id":3,
    "name":"DSC00044.JPG",
    "width":5152,
    "height":3864,
    "formats":{
      "thumbnail":{
        "name":"thumbnail_DSC00044.JPG",
        "hash":"thumbnail_DSC_00044_167687f904",
        "ext":".JPG",
        "mime":"image/jpeg",
        "width":208,
        "height":156,
        "size":9.9,
        "path":null,
        "url":"/uploads/thumbnail_DSC_00044_167687f904.JPG"
      },
      "large":{
        "name":"large_DSC00044.JPG",
        "hash":"large_DSC_00044_167687f904",
        "ext":".JPG",
        "mime":"image/jpeg",
        "width":1000,
        "height":750,
        "size":144.3,
        "path":null,
        "url":"/uploads/large_DSC_00044_167687f904.JPG"
      },
      "medium":{
        "name":"medium_DSC00044.JPG",
        "hash":"medium_DSC_00044_167687f904",
        "ext":".JPG",
        "mime":"image/jpeg",
        "width":750,
        "height":563,
        "size":91.9,
        "path":null,
        "url":"/uploads/medium_DSC_00044_167687f904.JPG"
      },
      "small":{
        "name":"small_DSC00044.JPG",
        "hash":"small_DSC_00044_167687f904",
        "ext":".JPG",
        "mime":"image/jpeg",
        "width":500,
        "height":375,
        "size":45.62,
        "path":null,
        "url":"/uploads/small_DSC_00044_167687f904.JPG"
      }
    },
    "hash":"DSC_00044_167687f904",
    "ext":".JPG",
    "mime":"image/jpeg",
    "size":2210.57,
    "url":"/uploads/DSC_00044_167687f904.JPG",
    "previewUrl":null,
    "provider":"local",
    "provider_metadata":null,
    "created_at":"2020-10-27T12:24:41.478Z",
    "updated_at":"2020-10-28T01:43:19.838Z"
  }
}
```

The current regex will ignore these images because of the capitalized JPG.

**Comment by OliverVorasai** [comment]
Also, the current regex pattern ignores capitalized extensions. For example:

Will match
```
http://localhost:1337/uploads/img_123.jpg
```

Will not match
```
http://localhost:1337/uploads/img_123.JPG
```

I ran into this problem because my camera saves images in this format. Adding `/gi` to the regex pattern seems to fix it okay.

**Comment by olivervorasai** [comment]
After looking further, this may be a nuxt issue and not related to magpie. The images are not generated in the html when static is true, regardless of magpie.

However, I also did notice the the current regex in magpie would not catch the `url("http://localhost:1337/uploads/small_test_Image1_c263df17a1.jpg")` styling. This should be in another issue though.

**Comment by eppidelic** [comment]
Hi! Sorry for the late reply!

I've been investigating this issue and I might have a fix to make this work with Vuetify. It seems `v-img` lazy loads the images so the actual url won't be found in the generated html or in the payload, but it seems to end up inside the js bundle with the rest of the scripts (the files with the auto generated names like `1ab23a1.js`). 

I can try to parse those files together with the pages' html and payload so that Magpie can also catch remote images from there.

As for the second issue, I'll try to reproduce it and let you know :)
