### ISSUE TITLE
Vue hydration replacing generated html

### ISSUE THREAD

**Issue by olivervorasai** [emiliobondioli/nuxt-magpie#4]
I have an issue where the HTML is generated correctly by nuxt-magpie, but the image src urls are replaced by the vue hydrations that were initially replaced by nuxt-magpie.

### HTML before generation

```
<template>
  <container>
    <img :src="`${strapiBaseUri + item.image.formats.small.url}`" />
  </container>
</template>
```

### HTML when vue hydrates

```
<template>
  <container>
    <img src="http://localhost:1337/uploads/small_DSC_00044_167687f904.JPG" />
  </container>
</template>
```

### HTML when vue does not hydrate
```
<template>
  <container>
    <img src="/_images/uploads-small_dsc_00044_167687f904.JPG" />
  </container>
</template>
```

### Questions
What we want is for vue to not hydrate again and to not replace the nuxt-magpie generated links, is this possible? How did you get around this?

### Steps to reproduce

I have included a production example of the problem here: https://friendly-lamarr-0a88a9.netlify.app/

When navigating to the `menu` page from any other page, vue hydration replaces the nuxt-magpie links. But, when loading the menu page directly the nuxt-magpie links stay in place.

**Comment by eppidelic** [comment]
How are you fetching the data for the menu?
AFAIK nuxt, even in full static mode, still runs the fetch calls once you navigate to the corresponding page (they mention it [here](https://nuxtjs.org/blog/going-full-static#current-issues)) and that's probably what's replacing your urls when you navigate. 

Until the nuxt team decides on it or gives us a way to prevent client-side fetching entirely, I'm using a workaround which seems to be working:
In my case I'm using vuex for state management and the fetch calls are used to populate the store, so I added a check in each 
fetch to stop the API calls if the requested data is already in the store.

**Comment by olivervorasai** [comment]
@emiliobondioli Using the store with nuxtServerInit in the store seems to be the best and the most appropriate way to handle this. I was originally using asyncData in each page. I have re-written the application to using the store and everything is working great!

### Side note

However there is one side effect. Nuxt-magpie seems to somehow catch the data in the store and the regex is matching against objects that have .JPG in their name. (I am using Strapi CMS and it automatically adds .JPG to their 'name' attribute)

Here are some examples:

This error showed up multiple times
```
 ERROR  Invalid URL: http://localhost:1337"},http:{browserBaseURL:"/"}},strapi:{user:a}}}(null,false,".JPG

  at onParseError (internal/url.js:243:9)
  at new URL (internal/url.js:319:5)
  at getImageUrls (node_modules\nuxt-magpie\lib\module.js:116:19)
  at replaceImagesInString (node_modules\nuxt-magpie\lib\module.js:80:18)
  at node_modules\nuxt-magpie\lib\module.js:93:22
  at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

This one didn't generate an error but it was 11,000 characters long and was still caught by the regex:
```
http://www.testtest.com/",open_hour:"11 AM",close_hour:"11 PM",
...
...
...
formats:{thumbnail:{name:"thumbnail_S8. Lemon-Grass Chicken.JPG
```

I got around this by adding the following code to `getImageUrls`

```
let url
try {
    url = new URL(match[0])
} catch (e) {
    continue
}
```

Of course this isn't a proper fix but works for now.

**Comment by eppidelic** [comment]
I've just noticed the same earlier today, there must be some issue with the regex. I solved it much the same way just ignoring malformed urls for now, but I'll tweak the regex a bit to avoid these issues. 
Thanks for your help in testing this!
