### ISSUE TITLE
Meta tags with image

### ISSUE THREAD

**Issue by Triloworld** [emiliobondioli/nuxt-magpie#8]
Found that head() images aren't taken into account when added like in page content.
I mean: twitter image, open-graph image etc.

This place is described here: https://nuxtjs.org/docs/2.x/features/meta-tags-seo

**Comment by eppidelic** [comment]
Hi!
I've tried to replicate your issue adding the social images both in nuxt.config and directly in the page component and they are correctly replaced with local copies:
![image](https://user-images.githubusercontent.com/22146599/119486407-80c38100-bd58-11eb-9cf9-6a9d5040a495.png)

Can you please provide a reproduction link or some details about your output?

**Comment by Triloworld** [comment]
Sorry. It was my fault.
None the less, there is hidden feature:
> extensions: ['jpg', 'jpeg', 'gif', 'png', 'webp', 'svg', 'xml'],
I get even svg, webp, and xml files. That is great ! :)

If my file don't have any extension then this option will give error (i cannot enter "/xyz/img_file").
Sorry for that issue.
All work fine :) +1
